---
- name: Ensure common utilities are installed
  ansible.builtin.apt:
    name:
      - rsync
      - curl
      - wget
      - git
    state: present
    update_cache: yes

- name: Update system packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 172800  # Only update if cache is older than 2 days
  register: system_update_result

- name: Display update results
  ansible.builtin.debug:
    msg: "System update completed. Changes made: {{ system_update_result.changed }}"
