---
- name: Create Nginx config directory
  ansible.builtin.file:
    path: "{{ app_dir }}/nginx"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Create Nginx Dockerfile
  ansible.builtin.copy:
    src: ../../local-dev/nginx/nginx.Dockerfile
    dest: "{{ app_dir }}/nginx/nginx.Dockerfile"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0644'

- name: Create production Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ app_dir }}/nginx/nginx.conf"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0644'
