services:
  app:
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
    container_name: ${APP_NAME}_app
    restart: unless-stopped
    expose:
      - "${APP_PORT}"
    volumes:
      - ./app:/app
      - ./posts:/posts
      - ./images:/images

networks:
  default:
    name: ${APP_NAME}_network
